version: '3.8'

services:
  # 1. База даних
  db:
    image: postgres:15-alpine
    container_name: ticket_postgres
    environment:
      POSTGRES_USER: ticket_user
      POSTGRES_PASSWORD: superpassword123
      POSTGRES_DB: ticket_booking_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - movieticket-network

  # 2. Основний .NET API
  backend:
    build:
      context: ./movieticket-server
      dockerfile: MovieTicket/Dockerfile
    container_name: ticket_backend
    ports:
      - "5016:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION_STRING}
    depends_on:
      - db
    networks:
      - movieticket-network

  # 3. Email Worker (.NET Фоновий сервіс)
  email-worker:
    build:
      context: ./movieticket-server
      dockerfile: MovieTicket.EmailWorker/Dockerfile
    container_name: ticket_email_worker

    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION_STRING}
    depends_on:
      - db
    networks:
      - movieticket-network

volumes:
  pgdata:

networks:
  movieticket-network:
    driver: bridge